### ISSUE TITLE
Create a GET API endpoint for all clients 

### ISSUE THREAD

**Issue by hopieyimmie** [hack4impact-calpoly/five-cities-food-pantry#11]
**Description**
Since the designs are not ready yet, create a GET API endpoint for MongoDB to retrieve all of the clients and their information attached.

**Acceptance Criteria**
API endpoint must be functional and has to work with MongoDB. Use console.log statements to see the data

**Additional Information**
Use mongoose to connect to the Client Schema and get users (just like bootcamp)
Getting All Clients /api/clients
Getting Individual Client /api/clients/[userId] 
- The userId is automatically generated in MongoDB

**Comment by ajesus7** [comment]
I'll do this one!
